language: node_js
node_js:
  - 8
  - 10
  - 12

script: npm run test:src

env:
  - NODE_ENV=test

jobs:
  include:
    - stage: other
      script: npm run lint
      node_js: lts/*
      name: Lint
    - script: npm run test:browser
      node_js: lts/*
      name: Browser Test
    - script: npm run coverage
      node_js: lts/*
      name: Coverage
      env:
        - NODE_ENV=dev

